#!/bin/sh

enabled="$(snapctl get enabled)"
if [ -z "${enabled}" -o "${enabled}" != "true" ]
then
    echo "Plume not yet enabled"
    exit 0
fi

export BASE_URL="$(snapctl get base-url)"
database_type="$(snapctl get db.type)"

if [ z"${database_type}" = z"sqlite" ]
then
    export DATABASE_URL=${SNAP_DATA}/plume.db
    export MIGRATION_DIR=migrations/sqlite
else
    # Must be postgres, so must have set db.url
    export DATABASE_URL="$(snapctl get db.url)"
    export MIGRATION_DIRECTORY=migrations/postgres
fi

ROCKET_ADDRESS="$(snapctl get listen.address)"
ROCKET_PORT="$(snapctl get listen.port)"
export ROCKET_SECRET_KEY="$(cat ${SNAP_COMMON}/rocket-secret-key)"
export SEARCH_INDEX="${SNAP_DATA}/search_index"
export MEDIA_UPLOAD_DIRECTORY="${SNAP_DATA}/media"

cd ${SNAP}
exec $@
