"project_identifier": "plume"
"api_key_env": CROWDIN_API_KEY
files:
  - source: /po/plume/plume.pot
    translation: /po/plume/%two_letters_code%.po
  - source: /po/plume-front/plume-front.pot
    translation: /po/plume-front/%two_letters_code%.po
