"project_id": 352097
"api_token_env": "CROWDIN_API_KEY"
preserve_hierarchy: true
files:
  - source: /po/plume/plume.pot
    translation: /po/plume/%two_letters_code%.po
  - source: /po/plume-front/plume-front.pot
    translation: /po/plume-front/%two_letters_code%.po
