-- Your SQL goes here
CREATE TABLE likes (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE NOT NULL,
    ap_url VARCHAR NOT NULL default '',
    creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
