-- Your SQL goes here
CREATE TABLE tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tag TEXT NOT NULL DEFAULT '',
    is_hastag BOOLEAN NOT NULL DEFAULT 'f',
    post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE NOT NULL
)
