-- Your SQL goes hereALTER TABLE ONLY posts ALTER COLUMN license SET DEFAULT 'CC-BY-SA';
ALTER TABLE ONLY posts ALTER COLUMN license SET DEFAULT 'CC-BY-SA';
ALTER TABLE ONLY instances ALTER COLUMN default_license SET DEFAULT 'CC-BY-SA';
